"""Train the GhostTrace secret-validity model.

The training set is generated by rendering realistic code/config lines that contain either
real-format secrets (random values in each provider's exact format) or the decoys that cause
false positives in keyword scanners (documentation placeholders, env-var references, test
fixtures, low-entropy dummies). Every line runs through the real detection engine, so the
features match what the scanner sees in production. A small amount of label noise is added
(real secrets in test folders, weak-but-real passwords) so the model learns soft boundaries.

Run:  python -m app.ml.train
"""

import base64
import json
import random
import string
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split

from ..detection.engine import is_sensitive_path, is_test_path, scan_text
from .features import FEATURE_NAMES, FindingContext, extract

ALNUM = string.ascii_letters + string.digits
UPPER_NUM = string.ascii_uppercase + string.digits
B64 = string.ascii_letters + string.digits + "+/"
URLSAFE = string.ascii_letters + string.digits + "-_"
HEX = "0123456789abcdef"


def rnd(alphabet: str, n: int, rng: random.Random) -> str:
    return "".join(rng.choice(alphabet) for _ in range(n))


def b64url(obj: dict) -> str:
    return base64.urlsafe_b64encode(json.dumps(obj).encode()).decode().rstrip("=")


def real_jwt(rng: random.Random) -> str:
    header = b64url({"alg": rng.choice(["HS256", "RS256"]), "typ": "JWT"})
    payload = b64url({"sub": str(rng.randint(1000, 99999999)), "iat": rng.randint(1_600_000_000, 1_760_000_000), "role": rng.choice(["admin", "user", "service"])})
    return f"{header}.{payload}.{rnd(URLSAFE, 43, rng)}"


def human_password(rng: random.Random) -> str:
    words = ["Summer", "Winter", "Dragon", "Monkey", "Falcon", "Tiger", "Galaxy", "Rocket", "Coffee", "Shadow"]
    return f"{rng.choice(words)}{rng.randint(10, 2025)}{rng.choice('!@#$%&*')}"


REAL = {
    "aws_key": lambda r: f'AWS_ACCESS_KEY_ID=AKIA{rnd(UPPER_NUM, 16, r)}',
    "aws_secret": lambda r: f'aws_secret_access_key = "{rnd(B64, 40, r)}"',
    "github_pat": lambda r: f'GITHUB_TOKEN=ghp_{rnd(ALNUM, 36, r)}',
    "google": lambda r: f'const mapsKey = "AIza{rnd(URLSAFE, 35, r)}";',
    "stripe_live": lambda r: f'stripe.api_key = "sk_live_{rnd(ALNUM, r.randint(24, 40), r)}"',
    "slack": lambda r: f'SLACK_BOT_TOKEN=xoxb-{r.randint(10**10, 10**11)}-{r.randint(10**10, 10**11)}-{rnd(ALNUM, 24, r)}',
    "openai": lambda r: f'OPENAI_API_KEY=sk-proj-{rnd(URLSAFE, 48, r)}',
    "sendgrid": lambda r: f'SENDGRID_API_KEY=SG.{rnd(URLSAFE, 22, r)}.{rnd(URLSAFE, 43, r)}',
    "npm": lambda r: f'//registry.npmjs.org/:_authToken=npm_{rnd(ALNUM, 36, r)}',
    "hf": lambda r: f'HF_TOKEN = "hf_{rnd(ALNUM, 34, r)}"',
    "jwt": lambda r: f'Authorization: Bearer {real_jwt(r)}',
    "private_key": lambda r: "-----BEGIN RSA PRIVATE KEY-----\n" + "\n".join(rnd(B64, 64, r) for _ in range(6)) + "\n-----END RSA PRIVATE KEY-----",
    "db_url": lambda r: f'DATABASE_URL=postgres://{r.choice(["app", "admin", "svc_api", "root"])}:{rnd(ALNUM, r.randint(14, 28), r)}@{r.choice(["db.prod", "10.0.3.12", "cluster0.mongo.net", "pg-main.internal"])}:5432/{r.choice(["app", "core", "billing"])}',
    "password_strong": lambda r: f'    "password": "{rnd(ALNUM + "!@#$%^&*", r.randint(12, 24), r)}",',
    "password_human": lambda r: f'db_password = "{human_password(r)}"',
    "env_password": lambda r: f'SMTP_PASSWORD={rnd(ALNUM, r.randint(12, 20), r)}',
    "generic_key": lambda r: f'api_key = "{rnd(HEX, 32, r)}"',
    "generic_secret": lambda r: f'client_secret: {rnd(URLSAFE, r.randint(24, 40), r)}',
    "email": lambda r: f'maintainer: {r.choice(["priya", "j.smith", "devops", "rahul.k", "admin"])}@{r.choice(["acme-corp.io", "fintrack.in", "gmail.com", "startup.dev"])}',
}

DECOY = {
    "aws_key_example": lambda r: 'AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE',
    "aws_key_x": lambda r: 'aws_access_key_id = "AKIAXXXXXXXXXXXXXXXX"',
    "aws_secret_example": lambda r: 'aws_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"',
    "github_dummy": lambda r: f'token = "ghp_{"x" * 36}"',
    "github_rep": lambda r: f'token = "ghp_{"0123456789abcdef" * 2}{"abcd"}"',
    "stripe_test": lambda r: f'STRIPE_KEY=sk_test_{rnd(ALNUM, 24, r)}',
    "jwt_doc": lambda r: 'token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"',
    "db_local": lambda r: f'DATABASE_URL=postgres://{r.choice(["postgres", "user", "test"])}:{r.choice(["postgres", "password", "test", "secret"])}@localhost:5432/{r.choice(["test", "dev", "app"])}',
    "db_template": lambda r: 'DATABASE_URL=mysql://user:${DB_PASSWORD}@db:3306/app',
    "password_placeholder": lambda r: f'password = "{r.choice(["changeme", "your_password", "<password>", "password123", "xxxxxxxx", "********", "secret123", "example-pass"])}"',
    "password_env_ref": lambda r: f'password = "{r.choice(["${DB_PASS}", "{{ db_password }}", "%(password)s"])}"',
    "env_password_ref": lambda r: f'DB_PASSWORD={r.choice(["changeme", "your-password-here", "REPLACE_ME", "xxxxxxxx", "<secret>"])}',
    "generic_placeholder": lambda r: f'api_key = "{r.choice(["your-api-key-goes-here", "YOUR_API_KEY_HERE_123456", "insert-your-key-here", "xxxxxxxxxxxxxxxxxxxxxxxx"])}"',
    "generic_lowent": lambda r: f'secret_key = "{r.choice(["aaaaaaaaaaaaaaaaaaaaaaab", "1234567890123456", "abcdefabcdefabcdef12"])}"',
    "generic_test": lambda r: f'api_key = "test_{rnd(HEX, 24, r)}"',
    "private_key_doc": lambda r: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA...your key here...\n" + "x" * 64 + "\n-----END RSA PRIVATE KEY-----",
}

SENSITIVE_PATHS = [".env", ".env.production", "config/secrets.yml", "deploy/prod.env", "settings.py", "config.json",
                   "docker-compose.yml", "terraform/prod.tfvars", ".npmrc", "credentials.json"]
SOURCE_PATHS = ["src/api/client.js", "app/services/payments.py", "scripts/deploy.sh", "lib/mailer.rb", "server/index.ts",
                "cmd/worker/main.go", "src/main/java/App.java", "infra/setup.sh", "bot.py", "notebooks/analysis.ipynb"]
TEST_PATHS = ["tests/test_auth.py", "spec/fixtures/users.json", "docs/configuration.md", "examples/quickstart.py",
              "README.md", ".env.example", "src/__tests__/api.test.js", "testdata/config.yaml", "samples/app.config"]


def _contexts(line: str, path: str, rng: random.Random) -> list[FindingContext]:
    out = []
    history = rng.random() < 0.25
    public = rng.random() < 0.8
    for m in scan_text(line, path):
        out.append(FindingContext(
            category=m.rule.category, base_severity=m.rule.severity, specific=m.rule.specific, secret=m.secret,
            entropy=m.entropy, placeholder=m.placeholder, test_path=is_test_path(path),
            sensitive_path=is_sensitive_path(path), history_only=history, line=line, public=public,
        ))
    return out


def build_dataset(n: int = 7000, seed: int = 7) -> tuple[np.ndarray, np.ndarray]:
    rng = random.Random(seed)
    X: list[list[float]] = []
    y: list[int] = []
    real_keys, decoy_keys = list(REAL), list(DECOY)
    while len(y) < n:
        is_real = rng.random() < 0.5
        if is_real:
            line = REAL[rng.choice(real_keys)](rng)
            path = rng.choice(TEST_PATHS) if rng.random() < 0.15 else rng.choice(SENSITIVE_PATHS + SOURCE_PATHS)
        else:
            line = DECOY[rng.choice(decoy_keys)](rng)
            path = rng.choice(TEST_PATHS) if rng.random() < 0.5 else rng.choice(SENSITIVE_PATHS + SOURCE_PATHS)
        label = int(is_real)
        if rng.random() < 0.04:  # label noise
            label = 1 - label
        for ctx in _contexts(line, path, rng):
            X.append(extract(ctx))
            y.append(label)
    return np.array(X), np.array(y)


def train_and_save(path: Path, verbose: bool = True) -> dict:
    X, y = build_dataset()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    model = GradientBoostingClassifier(n_estimators=250, max_depth=3, learning_rate=0.08, subsample=0.9, random_state=42)
    model.fit(X_train, y_train)
    proba = model.predict_proba(X_test)[:, 1]
    metrics = {"samples": int(len(y)), "roc_auc": round(float(roc_auc_score(y_test, proba)), 4)}
    if verbose:
        print(f"Samples: {metrics['samples']}  ROC AUC: {metrics['roc_auc']}")
        print(classification_report(y_test, (proba >= 0.5).astype(int), target_names=["decoy", "real"]))
        top = sorted(zip(FEATURE_NAMES, model.feature_importances_), key=lambda t: -t[1])[:8]
        print("Top features:", ", ".join(f"{n}={v:.3f}" for n, v in top))
    joblib.dump(model, path)
    return metrics


if __name__ == "__main__":
    train_and_save(Path(__file__).with_name("model.joblib"))
